default: &default
  adapter: postgresql
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: expressify_development

production:
  <<: *default
  prepared_statements: false
